api:
  url: https://localhost:3000/v1/
  key: authorisation-key
  currently-running-matches: ranked/servers
  
redis:
  enabled: true
  host: localhost
  port: 6379
  reconnect-sleep: 15

automove:
  poll-duration: 15